# Generated by Django 5.0.1 on 2024-02-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='listings.listing'),
        ),
    ]
